### ISSUE TITLE
ruTorrent can't find rtorrent

### ISSUE THREAD

**Issue by uruloke** [xombiemp/ultimate-torrent-setup#11]
Hello, I followed every step on a clean installation of Ubuntu 14.04, but when I get to the step in rutorrent, i get this error in the log of rutorrent:
```No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.```
When I run ```sudo service rtorrent start``` I get this response:
```rtorrent start/pre-start, process 3011```
And when I run ```sudo service rtorrent status``` I get this response:
```rtorrent stop/waiting```

**Comment by xombiemp** [comment]
Can you run rtorrent by just typing
`rtorrent`
?

**Comment by dot238** [comment]
I have the same issue. 

It looks like there is a config file missing. I get the error "Could not read resource file: ~/.rtorrent.rc" when running rtorrent.

If I copy the file ~/.config/rtorrent/ it doens't give that error but the service still doesn't start.

**Comment by mckinnon81** [comment]
Can you run rtorrent manually using this command - Replace YOURUSER with you username
rtorrent -n -o import=/home/YOURUSER/.config/rtorrent/rtorrent.rc

This will run rtorrent with out screen. You will be able to see any error message on the screen and determine why its not running.

Also ensure that sceen is installed - sudo apt-get install screen
