### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by binarybison** [xombiemp/ultimate-torrent-setup#12]
Installing libtorrent on a fresh ubuntu 15.04 install results in errors due to unmet dependencies. I was able to resolve these by running

sudo apt-get install --reinstall zlibc zlib1g zlib1g-dev

and

sudo aptitude install libssl-dev

Some of these packages should probably be added to the list of packages that are suggested to be installed at the beginning of the tutorial.

**Comment by mckinnon81** [comment]
Also screen is missing from the required packages.

When using this to install on Debian 8 (Jessie) - with some modifications I found the above packages missing as well as screen.

**Comment by xombiemp** [comment]
Fixed by adding zlib1g-dev libssl-dev
