### ISSUE TITLE
rtorrent install suggestion

### ISSUE THREAD

**Issue by 215** [xombiemp/ultimate-torrent-setup#13]
Just wanted to note that building rtorrent from source is unnecessary since rtorrent in the Ubuntu repos is already built with xmlrpc support.

**Comment by xombiemp** [comment]
I didn't realize it was built using --with-xmlrpc-c.  That's definitely an option, however you will be getting an older version; 0.9.2.

**Comment by xombiemp** [comment]
Thank you for your suggestion.  I added it as an option in the guide.
