### ISSUE TITLE
Issue with ProxyPass

### ISSUE THREAD

**Issue by exetico** [xombiemp/ultimate-torrent-setup#15]
Hello there,

After making small changes, i'm not able to get Couchpotato to work, with the https access.

The browser is redirecting to: "https://mydomain.com/#couchpotato (mydomain.com is ofc. the example)
but it only showing the index-file from the root of the normal webhost (/var/www).

The settings about couchpotato is below:
```
<Location /c>
        Require valid-user
        AuthType form
        AuthFormProvider file
        AuthFormLoginSuccessLocation /c
        AuthUserFile "/etc/apache2/passwd"
        AuthName "My Login"
        Session On
        SessionMaxAge 1800
        SessionCookieName session path=/
        SessionCryptoPassphrase PASS
        ErrorDocument 401 /login.html
        ProxyPass http://localhost:5050/couchpotato
        ProxyPassReverse http://localhost:5050/couchpotato
        RequestHeader set X-Forwarded-Proto "https"
        RequestHeader set X-Forwarded-Port "443"
    </Location>
```
Are you able to tell me, where i making an error? Everything else is running fine.

I'm at Debian, with Apache 2.4 - There was some small issues, but this stuff should work out of the box.

There isn't a folder called "c" in /var/www, and i guess thats the right way to do it, right?

Thanks for your help!

**Comment by Kerwood** [comment]
Hmm.. Not sure what you are trying to accomplish here. Its the proxy part that does not work?
You want to access https://mydomain.com and forward it to https://mydomain.com:5050, or ?

**Comment by xombiemp** [comment]
@exetico are you just trying to rename the url from /couchpotato to /c ?
If so, you also need to change your ProxyPass and ProxyPassReverse settings to /c and also the url_base setting in the couchpotato config to /c.

Then going to mydomain.com/c will show your couchpotato interface.

**Comment by exetico** [comment]
Well, i will try rephrase a bit.

By default the location is:
http://mydomain.com:5050/couchpotato

My Apache config:
```
    <Location /c>
        Require valid-user
        AuthType form
        AuthFormProvider file
        AuthFormLoginSuccessLocation /c
        AuthUserFile "/etc/apache2/passwd"
        AuthName "My Login"
        Session On
        SessionMaxAge 1800
        SessionCookieName session path=/
        SessionCryptoPassphrase 46CB5A52707D42A4ADCB1FA0E11D8D568CDDC1C8442F1EF0A4F938964B1EC9C5
        ErrorDocument 401 /login.html
        ProxyPass http://localhost:5050/couchpotato
        ProxyPassReverse http://localhost:5050/c
        RequestHeader set X-Forwarded-Proto "https"
        RequestHeader set X-Forwarded-Port "443"
    </Location>
````
Then i visit "https://mydomain.com/c" i'm ending at: "https://mydomain.com/c/#uchpotato/"
With the error-message "ERR_TOO_MANY_REDIRECTS"

I did change the couchpotato config to /c:
```
url_base = /c
```
So yes, that was the plan.

After reading what you're writing, i can see what i did wrong. Thanks for your support!
