### ISSUE TITLE
File/Directory Mask

### ISSUE THREAD

**Issue by 0mni** [xombiemp/ultimate-torrent-setup#18]
How do you deal with the file/directory mask and permissions ?

I have setup acl to combat most of the problems I am having, but curious what your solution was to the issue.

Otherwise A+ and awesome job on the guide.

**Comment by mckinnon81** [comment]
You may want to look at the umask setting in your rtorrent conf.

``system.umask.set = 0000 #set file permission created with rtorrent (777)``

Check the man pages on rtorrent for info on umask.

http://linux.die.net/man/1/rtorrent

**Comment by 0mni** [comment]
I figured out what he did, all the services are run by the same user.  I had setup a unique user for each service.  So to make things simple, plex, rtorrent, sonarr, and couchpotato are all on the same user.  Now there are no issues with file permissions :)
