### ISSUE TITLE
BlackHole vs ruTorrent

### ISSUE THREAD

**Issue by xeronick** [xombiemp/ultimate-torrent-setup#19]
This is not really an issue, I'm just curious. For both CouchPotato and Sonarr you're using BlackHole instead of ruTorrent. Why are you not using ruTorrent for these?

**Comment by xombiemp** [comment]
Here are some reasons I've found:

- Sonarr is unable to remove torrents that have finished seeding when using rTorrent

- auto unrar plugin with rutorrent is messy with this method and Sonarr doesn't have unraring yet

- hardlinking will be done from sonarr so you will need to create a filter in the rutorrent auto tools plugin to exclude downloads from Sonarr

- you will not be able to use forms auth and will have to use basic auth in Apache

-  With this method some of the torrent handling config is split between rutorrent and Sonarr (hard linking, unraring eventually, delete after seed time/ration maybe eventually)

Using blackhole seems cleaner to me.  All the torrent handling is done in rutorrent.  Unraring works, you set up seed time or ratio rules per tracker, and Sonarr is always dealing with a hard link of the file so seeding is never disturbed.  I haven't seen any benefit to compel me to attempt to get a setup going with the rtorrent provider in Sonarr and CouchPotato.
