### ISSUE TITLE
autounpacking not working

### ISSUE THREAD

**Issue by c0pp3r** [xombiemp/ultimate-torrent-setup#20]
When following the instructions torrents that are rared don't seem to autounpack. Sonarr doesn't automatically pick things up because of this.

**Comment by xombiemp** [comment]
I know there was an issue before that required rtorrent to restart after enabling auto unpacking in the settings before it would work.  So try restarting rtorrent and see if auto unpacking works.

**Comment by c0pp3r** [comment]
Tried restarting rtorrent as well as restarting rutorrent and the whole server. Just setup logging and AutoUnpack didn't even create any logs, automove worked fine and watch is working. Manual unpack also works fine.

**Comment by xombiemp** [comment]
I just tried the guide from scratch and auto unpack worked as expected.  Are you looking in the complete folder instead of the download folder?  The unpacked archive will be in the complete folder.

**Comment by c0pp3r** [comment]
hmm this must be on my end somehow. Sound I do a reinstall of rutorrent, rtorrent or both?

**Comment by xombiemp** [comment]
Maybe try the guide from scratch using the new Ubuntu 16.04.
