### ISSUE TITLE
Error restarting rtorrent

### ISSUE THREAD

**Issue by scouseman** [xombiemp/ultimate-torrent-setup#22]
I have run this code twice now on my Ubuntu 16.04 server and I get as far as:
** sudo update-rutorrent**

and it fails with error:

`Job for rtorrent.service failed because the control process exited with error code. See "systemctl status rtorrent.service" and "journalctl -xe" for details.`

The systemctl error log is below:

`May 11 20:23:33 mail.supplyanddemmand.tk systemd[4997]: rtorrent.service: Failed at step USER spawning /usr/bin/screen: N
May 11 20:23:33 mail.supplyanddemmand.tk systemd[1]: rtorrent.service: Control process exited, code=exited status=217
May 11 20:23:33 mail.supplyanddemmand.tk systemd[1]: Failed to start rTorrent.
May 11 20:23:33 mail.supplyanddemmand.tk systemd[1]: rtorrent.service: Unit entered failed state.
May 11 20:23:33 mail.supplyanddemmand.tk systemd[1]: rtorrent.service: Failed with result 'exit-code'.
May 11 20:23:33 mail.supplyanddemmand.tk systemd[1]: rtorrent.service: Service hold-off time over, scheduling restart.
May 11 20:23:33 mail.supplyanddemmand.tk systemd[1]: Stopped rTorrent.
May 11 20:23:33 mail.supplyanddemmand.tk systemd[1]: Starting rTorrent...
`
Any assistance would be most appreciated.
Cheers

**Comment by xombiemp** [comment]
Can you post the contents of your rtorrent.service file?

**Comment by scouseman** [comment]
`[Unit]
Description=rTorrent
After=network.target

[Service]
User=scouseman
Group=scouseman

Type=forking
KillMode=none
Restart=on-failure
ExecStart=/usr/bin/screen -d -m -fa -S rtorrent /usr/bin/rtorrent -n -o import=/root/.config/rtorrent/rtorrent.rc
ExecStop=/usr/bin/killall -w -s 2 /usr/bin/rtorrent

[Install]
WantedBy=multi-user.target`

Cheers

**Comment by xombiemp** [comment]
I found the problem.  When compiling rtorrent it installs in /usr/local/bin and not /usr/bin, so the startup script is failing.  I updated the wiki to include this command that will fix the problem:

sudo ln -s /usr/local/bin/rtorrent /usr/bin/

Thanks for the report.

**Comment by scouseman** [comment]
Hi, I am still having the same problem with this script failing when I restart rtorrent, I reinstalled ubuntu and started again from a fresh system, but I am still getting the same error.

Cheers

**Comment by xombiemp** [comment]
I've tried but can't reproduce this.  Can you post the full logs that you get from running
```sudo journalctl -u rtorrent.service```

**Comment by scouseman** [comment]
Unfortunitly I currently away on vacation and wont be back for several weeks, I will post the logs on my return. I have a feeling it may have something to do with me running your script on a OVH dedicated servers, I believe there are some issues surrounding these servers, as I have noticed there are several scripts soley written for OVH and non OVH servers on the torrent invites forum.

**Comment by scouseman** [comment]
I've managed to reproduce the error on my server, here is the log output:
`May 19 15:17:35 ns3043093.*.eu systemd[1]: Failed to start rTorrent.
May 19 15:17:35 ns3043093.*.eu systemd[1]: rtorrent.service: Unit entered failed state.
May 19 15:17:35 ns3043093.*.eu systemd[1]: rtorrent.service: Failed with result 'exit-code'.
May 19 15:17:35 ns3043093.*.eu systemd[1]: rtorrent.service: Service hold-off time over, scheduling restart.
May 19 15:17:35 ns3043093.*.eu systemd[1]: Stopped rTorrent.
May 19 15:17:35 ns3043093.*.eu systemd[1]: Starting rTorrent...
May 19 15:17:35 ns3043093.*.eu systemd[20815]: rtorrent.service: Failed at step USER spawning /usr/bin/screen: No such process
May 19 15:17:35 ns3043093.*.eu systemd[1]: rtorrent.service: Control process exited, code=exited status=217`

**Comment by xombiemp** [comment]
Can you make sure that /usr/bin/screen and /usr/bin/rtorrent both exist in those locations?

**Comment by scouseman** [comment]
yes they do.

**Comment by xombiemp** [comment]
It looks like your rtorrent.rc file is under the /root directory.  Does your scouseman user have permissions to read that?

**Comment by Fredda-2** [comment]
I can report that I get the same problem as scouseman

**Comment by scouseman** [comment]
Thanks very much that was in fact the cause of the issues I was having the file permissions on the rtorrent.rc file.
