### ISSUE TITLE
Update wiki to use ssl from let's encrypt

### ISSUE THREAD

**Issue by mcaron1234** [xombiemp/ultimate-torrent-setup#23]
Can you provide instructions to use this setup with the free let's encrypt ssl certificate service?  For some the service doesn't recognize apache-portal.conf.

**Comment by xombiemp** [comment]
The guide now uses Let's Encrypt. https://github.com/xombiemp/ultimate-torrent-setup/commit/08573678ee30479d665b352726121a1272253003
