### ISSUE TITLE
Error when compiling/installing XMLRPC-C

### ISSUE THREAD

**Issue by Zoink5** [xombiemp/ultimate-torrent-setup#26]
Hello,

I'm running into an issue when trying to compile xmlrpc-c with torrent. I get:
`configure: error: Could not compile XMLRPC-C test.` in the terminal window.

Strange, because the guide worked flawlessly on my computer the first time. Now this error is here I can't get past this. Followed guide step by step.

Any help is greatly appreciated - and great job on the guide. Really helps me understand more of the Linux language.

**Comment by xombiemp** [comment]
For some reason when compiling xmlrpc-c it doesn't put xmlrpc-c-config in /usr/local/bin like it used to.  That is what is causing this issue.  I'm guessing it's a bug with xmlrpc-c that will eventually be fixed but for now we can manually point to the file like this:
sudo ./configure --with-xmlrpc-c=/usr/local/src/xmlrpc-c/xmlrpc-c-config

I updated the wiki to reflect this.
