### ISSUE TITLE
svn.rutorrent.org down

### ISSUE THREAD

**Issue by chaoticdude** [xombiemp/ultimate-torrent-setup#30]
svn for rutorrent is down; is there another location I can find the filemanager/fileshare plugins? I've tried searching the internet but everything points to that SVN. If not, are they required for this to work?

**Comment by Amdingo** [comment]
Here for the same reason as well.  Still searching though!

**Comment by xombiemp** [comment]
I've disabled trying to install those plugins in 62b6b60f2871fce5db86faeb30117687aa0b90c7
If the projects are hosted somewhere else in the future I will reenable them.

**Comment by xombiemp** [comment]
I reenabled the filemanager and fileshare plugins by using repo https://github.com/nelu/rutorrent-thirdparty-plugins/. b263591aa36081caa0317ad7e7e741794a9d9b20

**Comment by chaoticdude** [comment]
How do I update my update-rutorrent to point to these?

**Comment by xombiemp** [comment]
Change
filemanager_svn="http://svn.rutorrent.org/svn/filemanager/trunk"
to 
filemanager_svn="https://github.com/nelu/rutorrent-thirdparty-plugins/trunk"

**Comment by chaoticdude** [comment]
Thanks so much for your help!!
