### ISSUE TITLE
plexupdate.sh complains about conf file in update-plexmediaserver

### ISSUE THREAD

**Issue by mcaron1234** [xombiemp/ultimate-torrent-setup#32]
When I run update-plexmediaserver there is a warning:

`sudo update-plexmediaserver
WARNING: Specifying config file as last argument is deprecated. Use --config <path> instead.
`

I fixed by modifying update-plexmediaserver by adding --config /opt/plexupdate/plexupdate.conf

`/opt/plexupdate/plexupdate.sh -u -a -d --config /opt/plexupdate/plexupdate.conf`

btw, thanks so much for this setup, its been extremely helpful.

**Comment by xombiemp** [comment]
Thanks.  Fixed in d1c8c131d470a0b3fb12e262e71ebea2a6fb05a3
