### ISSUE TITLE
rtorrent/rutorrent don't pick magnet files created by couchpotato

### ISSUE THREAD

**Issue by panprofes** [xombiemp/ultimate-torrent-setup#33]
Couchpotato creating .magnet files in watch directory, byt torrent app can't  use them. How to fix it? Can couchpotato save .torrent files instead of .magnet?

**Comment by extra** [comment]
Open Couchpotato -> Settings -> Downloaders.  Show Advanced.  Under Black Hole there is an option: "If magnet file conversion fails, write down the magnet link in a .magnet file instead."  Uncheck that and you should be set.

**Comment by xombiemp** [comment]
I'm not familiar with .magnet files but it sounds like @extra 's solution is what you are looking for.

**Comment by panprofes** [comment]
I found solution for this error. @extra unchecking this box just stops making .magnet files. @xombiemp  torcache.net is closed so I replaced it by  'http://btcache.me/torrent/%s.torrent', in CPS/couchpotato/core/_base/downloader/main.py . It resolves all problems with not downloading movies by coachpotato 💃
