### ISSUE TITLE
Couchpotato can't convert magnet files into torrent

### ISSUE THREAD

**Issue by panprofes** [xombiemp/ultimate-torrent-setup#34]
torcache.net is closed so I replaced it by 'http://btcache.me/torrent/%s.torrent', in CPS/couchpotato/core/_base/downloader/main.py . Now it makes torrent files but they are not converted in right way so torrent can't run them.

**Comment by xombiemp** [comment]
Sounds like a Couchpotato issue?  Or maybe a btcache.me issue?
I don't know, but it doesn't have to do with this project.
Couchpotatos repo is here https://github.com/CouchPotato/CouchPotatoServer
