### ISSUE TITLE
0 peers 0 seeds

### ISSUE THREAD

**Issue by pguizeline** [xombiemp/ultimate-torrent-setup#38]
First let me thank @xombiemp for this awesome Wiki and scripts that helped me build the sexiest seedbox I've ever seen!

I just wanted to ask if anyone has seen this kind of behavior over ruTorrent screen, as the screenshots posted below:

Here we see 0 peers and 0 torrents for all files that are seeding.
![2016-12-01 18_55_18-rutorrent v3 7](https://cloud.githubusercontent.com/assets/13438826/20812359/5f01ecc4-b7f8-11e6-80e2-0613079ce5e3.png)

But when you check over the trackers stats, or over the tracker website, you can see values.
![2016-12-01 18_56_11-rutorrent v3 7](https://cloud.githubusercontent.com/assets/13438826/20812366/62bfa3a6-b7f8-11e6-8d5a-6cb9b36f45c8.png)

I'm puzzled by this, is it the tracker I'm using? Is it Couchpotato and/or Sonarr TorrentBlackhole effect? Any kind of input would be greatly appreciated! Thanks in advance for any help!

**Comment by xombiemp** [comment]
Glad you liked the guide.  I'm not sure about this.  Maybe ask over at the rutorrent repo https://github.com/Novik/ruTorrent
