### ISSUE TITLE
Headphones

### ISSUE THREAD

**Issue by chaoticdude** [xombiemp/ultimate-torrent-setup#39]
Hi -
Not really an issue, more of a request--I apologize if this is the wrong forum for this (I'm not familiar with Github..). 

Anyways, is it possible to integrate Headphones into this setup so it's a tv/movie/music badass beast? 

Further, thanks @xombiemp for writing this up. I now spend 0-5% of my time during the week maintaining my TV and movies.

**Comment by xombiemp** [comment]
I added instructions for Lidarr.
