### ISSUE TITLE
Autotools cant see /mnt/ directories

### ISSUE THREAD

**Issue by chaoticdude** [xombiemp/ultimate-torrent-setup#40]
The hard drive that houses my /data/ dir is too small, I want to move it to /mnt/d/data/ . I have filemanager configured and it is working as I can see the total free space available. The autotools, however, continue to point to /data/ and will not let me save the new changes to /mnt/d/data/ . . . 

How can I fix this and/or force autotools to look at /mnt/d/data/ ?

**Comment by xombiemp** [comment]
Make sure you have the right path configured in rutorrent/conf/config.php in the $topDirectory variable.  If you still have problems, try asking on the rutorrent repo https://github.com/Novik/ruTorrent
