### ISSUE TITLE
rtorrent.service: Failed at step EXEC spawning /usr/bin/rtorrent

### ISSUE THREAD

**Issue by Synopis** [xombiemp/ultimate-torrent-setup#44]
For some reason the commands below aren't copying or at the very least installing rtorrent. There's no folder or anything in /usr/bin/.

cd /usr/local/src

sudo git clone https://github.com/rakshasa/rtorrent.git

cd rtorrent

sudo ./autogen.sh

sudo ./configure --with-xmlrpc-c=/usr/local/src/xmlrpc-c/xmlrpc-c-config

sudo make

sudo make install

sudo ln -s /usr/local/bin/rtorrent /usr/bin/

sudo ldconfig

sudo adduser --system --home=/var/lib/rtorrent --group rtorrent

sudo adduser rtorrent media

**Comment by lailoken503** [comment]
Isn't there a ./configure option to define installation path? Using your example, 
`./configure` --prefix=/usr/bin --with-xmlrpc-c=/usr/local/src/xmlrpc-c/xmlrpc-c-config`

**Comment by xombiemp** [comment]
I've updated to guide to revert rtorrent to a know working commit until the Master branch starts working again.  Try compiling rtorrent using the guide again.
