### ISSUE TITLE
connection to rtorrent is not established

### ISSUE THREAD

**Issue by SemperFratres** [xombiemp/ultimate-torrent-setup#46]
I just followed this instruction, and I get a message about "connection to rtorrent is not established".
I ran this code
`rtorrent -n -o import=/home/tim/.config/rtorrent/rtorrent.rc`
and get the message that rtorrent is not installed. I ran thru and installed everything from rtorrent down and still get that message.
Any help would be appreciated.

**Comment by xombiemp** [comment]
I've updated to guide to revert rtorrent to a know working commit until the Master branch starts working again.  Try compiling rtorrent using the guide again.
