### ISSUE TITLE
mkdir data rather than mkdir /data

### ISSUE THREAD

**Issue by SemperFratres** [xombiemp/ultimate-torrent-setup#47]
@xombiemp 
First, thank you for correcting those links. After that happened, the issues I had went away, but I ran into another issue.
You have us mkdir at /data. As I downloaded some torrents, ruTorrent stopped working because there was no more space on the disk. I have a 2TB server, and had only gotten about 15 torrents. There was no way it was full. After a little thinking (I am new to Linux), I realized that the data directory was in root. There is no space there. I was able to move everything to /home, but ruTorrent still would not restart, so I had to wipe the server and start again, this time making the directory in /home using mkdir data.

One other thing I came across was trying to configure Plex.  The user needs to ssh into the server in able to access http://ubnutu.server.local.ip:32400/web. If using a Linux machine to do so, using
 `ssh ip.address.of.server -L 8888:localhost:32400` 
will get you access via a browser. You can then use the address you provided. If using Windows, PuTTY or something similar will get you ssh access.

Thanks again for the wiki.
Semper~

**Comment by xombiemp** [comment]
Thanks for the feedback.  I modified the wiki to clarify that /data is just an example path and I added a link to a Plex article that describes setting up an ssh tunnel for servers that are on a different network.
