### ISSUE TITLE
Multiple Users?

### ISSUE THREAD

**Issue by SemperFratres** [xombiemp/ultimate-torrent-setup#49]
@xombiemp I have finally got this setup and working correctly. Thanks again for the wiki.
Someone asked me a question and I don't know the answer to it.
Can this setup be used for multiple users/usernames?
Is it as simple as installing/editing config files under that username?
I am assuming rtorrent will need a .session for that username. Is that as simple as installing it under that username? Or copying/editing from one username to another?
Thanks again.

**Comment by xombiemp** [comment]
I've never set up multiple users for rtorrent.  I think it would take significant modifications to what this guide sets up.
