### ISSUE TITLE
Can't read resource file

### ISSUE THREAD

**Issue by SemperFratres** [xombiemp/ultimate-torrent-setup#51]
@xombiemp 
Things were running good and then rutorrent stopped connecting to rtorrent.
I have rebooted and restarted rtorrent multiple times, but nothing is working.
rTorrent is still running and downloading from Sonarr and CP, but when running rtorrent from the command line, I get the following message:
`could not read resource file: ~/.rtorernt.rc`
 Nothing changed from the time it was working to 10  mins later when it stopped working.
http://i.imgur.com/prWDFKU.png

edit:
The rtorrent service is pointing to the correct location of rtorrent.rc
http://i.imgur.com/RLfq8g7.png

**Comment by xombiemp** [comment]
What is the command you are using to start rtorrent?

**Comment by SemperFratres** [comment]
sudo service rtorrent start

Sonarr and CP are sending the torrents. rTorrent is running fine. Things are downloading fine (I'm getting messages via join and slack), but ruTorrent is not running because rtorrent can't load the .rtorrent.rc file. 
Have checked and the file is there.

**Comment by SemperFratres** [comment]
Going to try a re-install of rtorrent.
I assume the dir I need to remove is `/usr/local/src/rtorrent`. Was going to try a make uninstall, but that is not an option since there is not an uninstall package in here.
Are there any other files I need to remove?
