### ISSUE TITLE
Couch Potato not creating cp.torrent.fail files instead of snatching movies

### ISSUE THREAD

**Issue by akasoldats** [xombiemp/ultimate-torrent-setup#52]
I'm not sure if this is related to CP specifically, the overall torrent setup, or user error on my part however every movie added via CP creates a *.cp(tt########).torrent.fail file in the watch directory. If I nab a torrent from CP and past the ui into rtorrent it works fine. Any ideas what might cause this?

**Comment by akasoldats** [comment]
Upon further inspection it looks like it starts out as a .torrent file and then eventually is changed into a .torrent.fail file. :/

**Comment by xombiemp** [comment]
Rutorrent is the process that is adding .fail to the torrent file because it is failing to add the torrent for some reason.

In couchpotato, go to Setting General and make sure folder CHMOD is 0775 and file CHMOD is 0664.

**Comment by akasoldats** [comment]
Those were already set. Any other ides? Is there an error log somewhere I can check to see why rutorrent is failing?

**Comment by skluthe** [comment]
Set a cronjob to look at your watch folder and rename any .fail file to remove the .fail extension and set the permissions using chmod. If you need a specific cron command let me know.

**Comment by xombiemp** [comment]
Guide now uses Radarr instead of CouchPotato.
