### ISSUE TITLE
problem with letsencrypt

### ISSUE THREAD

**Issue by NOsteyr** [xombiemp/ultimate-torrent-setup#56]
Hello there.
I have a problem when i install letsencrypt.
My domain is with the letter Ø and for some reason i fail to configure letsencrypt with this letter.

**Comment by skluthe** [comment]
It may be worth looking at using Caddy as a reverse proxy in front of your server. It allows you to redirect traffic to different servers within your network and automatically sets up letsencrypt for you. It will take any user error out of the equation and provide you with better security.

**Comment by xombiemp** [comment]
Try to reach out for help from letsencrypt directly.
