### ISSUE TITLE
rtorrent not starting

### ISSUE THREAD

**Issue by chaoticdude** [xombiemp/ultimate-torrent-setup#57]
My rtorrent service isn't starting. Not sure how to fix, here is the status...any insight would be much appreciated. 

● rtorrent.service - rTorrent
   Loaded: loaded (/etc/systemd/system/rtorrent.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Sat 2017-11-11 10:28:33 MST; 3min 2s ago
  Process: 18193 ExecStart=/usr/bin/rtorrent -n -o import=/var/lib/rtorrent/rtorrent.rc (code=exited, status=255)
 Main PID: 18193 (code=exited, status=255)

Nov 11 10:28:33 CHAOTICSERVER systemd[1]: rtorrent.service: Unit entered failed state.
Nov 11 10:28:33 CHAOTICSERVER systemd[1]: rtorrent.service: Failed with result 'exit-code'.
Nov 11 10:28:33 CHAOTICSERVER systemd[1]: rtorrent.service: Service hold-off time over, scheduling restart.
Nov 11 10:28:33 CHAOTICSERVER systemd[1]: Stopped rTorrent.
Nov 11 10:28:33 CHAOTICSERVER systemd[1]: rtorrent.service: Start request repeated too quickly.
Nov 11 10:28:33 CHAOTICSERVER systemd[1]: Failed to start rTorrent.

**Comment by crsantos** [comment]
1. **IF** you have logs enabled ([check here on the config](https://github.com/xombiemp/ultimate-torrent-setup/blob/master/rtorrent.rc#L107)) They may trying to be written on `/tmp` which `rtorrent` user may not have access.
If this is the case:  **edit** your `httpd.service` file and add the following: `PrivateTmp=false`

**Comment by cafeoliveira** [comment]
Hello .. Good evening...
I have the same problem...
This is not 0% ...
the strangest thing is that this has already been working, I have tested in several machines and the result is the same ..... 0%

Do they have a solution?
thank you

**Comment by cafeoliveira** [comment]
this was the tutorial I followed: 
https://github.com/xombiemp/ultimate-torrent-setup/wiki
and already worked very well .... was it some update ... ????

**Comment by xombiemp** [comment]
rTorrent code has been update and the guide is using the master branch again.  It should work now.
