### ISSUE TITLE
Not an issue, but a request

### ISSUE THREAD

**Issue by captnslw** [xombiemp/ultimate-torrent-setup#58]
Hi! great guide, great details. But could you do one were you swap out sonarr for sickrage? as sickrage works better with torrent sites for legacy search etc. 

Thanks again. Great guide!

**Comment by crsantos** [comment]
I'm sorry, excuse me for trying to give my 2 cents here.

I was a user of sickbeard, sickrage and none of them is any better than sonarr.
If you struggle to find a working API for your current tracker that works with Sonarr, I suggest you to try [Jackett](https://github.com/Jackett/Jackett).

With Jackett you can "emulate" API support even for searching.

**Comment by xombiemp** [comment]
Sorry, I prefer Sonarr.
