### ISSUE TITLE
rTorrrent not starting after reboot

### ISSUE THREAD

**Issue by mithrandir86** [xombiemp/ultimate-torrent-setup#6]
I must express my gratitude for your fantastic guide. For this type of work I am heavily dependent on well-written guides like this.

I followed your guide to the letter except that I used the most recent versions of rtorrent and libtorrent. I recognize now that this may have caused problems.

I got everything working and rtorrent and rutorrent were talking to each other. I rebooted and rtorrent failed to load, or at least failed to load in a way that rutorrent could see it. 

I moved a copy of the rtorrent config file to the home directory and called it .rtorrent. I used putty to start rtorrent, then quit, then started rTorrent as a service. That seems to work OK. 

I am wondering if there is something in init script (or another script) that is version dependent and that I can amend. I've looked over them and I couldn't find anything, but admittedly I am not well-versed in this endeavor. Or, in the alternative, I should move to the versions you used in the guides if that is the problem. 

Any help that you could offer would be greatly appreciated.

**Comment by xombiemp** [comment]
I just updated the guide to use the latest libtorrent and rtorrent from the git repos.  Try it out and see if it fixes your problem.

**Comment by mithrandir86** [comment]
Thanks for the information! Really appreciate it.

Now, assuming that I followed your earlier instructions (except for the
above amendments) how would I proceed? Would I remove something first or
just start by installing rtorrent/libtorrent based on your instructions?

**Comment by mithrandir86** [comment]
Actually I got everything working. The guide was easy to understand. thank
you for all your help.
