### ISSUE TITLE
Failed to start The Apache HTTP Server.

### ISSUE THREAD

**Issue by Dolkis** [xombiemp/ultimate-torrent-setup#60]
When Im trying to restart the apache2 this comes up:

root@ubuntu-media:~# sudo service apache2 restart
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.

root@ubuntu-media:~# systemctl status apache2.service
● apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─apache2-systemd.conf
   Active: failed (Result: exit-code) since Fri 2018-07-20 20:19:34 UTC; 1min 51s ago
  Process: 5197 ExecStop=/usr/sbin/apachectl stop (code=exited, status=1/FAILURE)
  Process: 23365 ExecStart=/usr/sbin/apachectl start (code=exited, status=1/FAILURE)
 Main PID: 13174 (code=exited, status=0/SUCCESS)

Jul 20 20:19:34 ubuntu-media systemd[1]: Starting The Apache HTTP Server...
Jul 20 20:19:34 ubuntu-media apachectl[23365]: /usr/sbin/apachectl: 18: /etc/apache2/envvars: 0002: not found
Jul 20 20:19:34 ubuntu-media apachectl[23365]: AH00526: Syntax error on line 21 of /etc/apache2/sites-enabled/apache-portal.conf:
Jul 20 20:19:34 ubuntu-media apachectl[23365]: SSLCertificateFile: file '/etc/letsencrypt/live/yourdomain.com/fullchain.pem' does not exist or is empty
Jul 20 20:19:34 ubuntu-media apachectl[23365]: Action 'start' failed.
Jul 20 20:19:34 ubuntu-media apachectl[23365]: The Apache error log may have more information.
Jul 20 20:19:34 ubuntu-media systemd[1]: apache2.service: Control process exited, code=exited status=1
Jul 20 20:19:34 ubuntu-media systemd[1]: apache2.service: Failed with result 'exit-code'.
Jul 20 20:19:34 ubuntu-media systemd[1]: Failed to start The Apache HTTP Server.
.

 journalctl -xe
Jul 20 20:18:50 ubuntu-media systemd[1]: apache2.service: Control process exited, code=exited status=1
Jul 20 20:18:50 ubuntu-media systemd[1]: apache2.service: Failed with result 'exit-code'.
Jul 20 20:18:50 ubuntu-media systemd[1]: Failed to start The Apache HTTP Server.
-- Subject: Unit apache2.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit apache2.service has failed.
--
-- The result is RESULT.
Jul 20 20:19:11 ubuntu-media systemd[1]: Starting The Apache HTTP Server...
-- Subject: Unit apache2.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit apache2.service has begun starting up.
Jul 20 20:19:11 ubuntu-media apachectl[23332]: /usr/sbin/apachectl: 18: /etc/apache2/envvars: 0002: not found
Jul 20 20:19:11 ubuntu-media apachectl[23332]: AH00526: Syntax error on line 21 of /etc/apache2/sites-enabled/apache-portal.conf:
Jul 20 20:19:11 ubuntu-media apachectl[23332]: SSLCertificateFile: file '/etc/letsencrypt/live/yourdomain.com/fullchain.pem' does not exist or is empty
Jul 20 20:19:11 ubuntu-media apachectl[23332]: Action 'start' failed.
Jul 20 20:19:11 ubuntu-media apachectl[23332]: The Apache error log may have more information.
Jul 20 20:19:11 ubuntu-media systemd[1]: apache2.service: Control process exited, code=exited status=1
Jul 20 20:19:11 ubuntu-media systemd[1]: apache2.service: Failed with result 'exit-code'.
Jul 20 20:19:11 ubuntu-media systemd[1]: Failed to start The Apache HTTP Server.
-- Subject: Unit apache2.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit apache2.service has failed.
--
-- The result is RESULT.
Jul 20 20:19:34 ubuntu-media systemd[1]: Starting The Apache HTTP Server...
-- Subject: Unit apache2.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit apache2.service has begun starting up.
Jul 20 20:19:34 ubuntu-media apachectl[23365]: /usr/sbin/apachectl: 18: /etc/apache2/envvars: 0002: not found
Jul 20 20:19:34 ubuntu-media apachectl[23365]: AH00526: Syntax error on line 21 of /etc/apache2/sites-enabled/apache-portal.conf:
Jul 20 20:19:34 ubuntu-media apachectl[23365]: SSLCertificateFile: file '/etc/letsencrypt/live/yourdomain.com/fullchain.pem' does not exist or is empty
Jul 20 20:19:34 ubuntu-media apachectl[23365]: Action 'start' failed.
Jul 20 20:19:34 ubuntu-media apachectl[23365]: The Apache error log may have more information.
Jul 20 20:19:34 ubuntu-media systemd[1]: apache2.service: Control process exited, code=exited status=1
Jul 20 20:19:34 ubuntu-media systemd[1]: apache2.service: Failed with result 'exit-code'.
Jul 20 20:19:34 ubuntu-media systemd[1]: Failed to start The Apache HTTP Server.
-- Subject: Unit apache2.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit apache2.service has failed.
--
-- The result is RESULT.

**Comment by xombiemp** [comment]
These lines of the log you posted tell you exactly what the problem is:

Jul 20 20:19:34 ubuntu-media apachectl[23365]: AH00526: Syntax error on line 21 of /etc/apache2/sites-enabled/apache-portal.conf:
Jul 20 20:19:34 ubuntu-media apachectl[23365]: SSLCertificateFile: file '/etc/letsencrypt/live/yourdomain.com/fullchain.pem' does not exist or is empty
