### ISSUE TITLE
fileshare

### ISSUE THREAD

**Issue by mehdi198080** [xombiemp/ultimate-torrent-setup#63]
hi

fileshare not working and getting error.

plz check

**Comment by xombiemp** [comment]
I don't maintain that plugin.  Submit a bug report to the repo owner.

**Comment by mehdi198080** [comment]
the error is no such file

**Comment by mehdi198080** [comment]
let me describe you what happen exactly 

this command gave me error
sudo mv ~/configs/plugins.ini -o /var/www/rutorrent/conf/plugins.ini
I change it with this 
sudo mv ~/configs/plugins.ini  /var/www/rutorrent/conf/plugins.ini

after completed fileshare missed and I install it of another source

my setting is 
<?php

// duration & links limits
// 0 = unlimited
$limits['duration'] = 24;        // maximum duration hours
$limits['links'] = 0;   //maximum sharing links per user

// extra
$limits['nolimit'] = 0; // allow unlimited duration (=~ 100 years) with duration = 0 (the maximum duration limit is kept) [1 = yes | 0 = no]

// path on domain where a symlink to share.php can be found
// example: http://mydomain.com/share.php
$downloadpath = 'https://mehdisa.xyz/public/share.php';

?>

pls kindly check it

**Comment by mehdi198080** [comment]
`<?php`

// duration & links limits
// 0 = unlimited
$limits['duration'] = 24;        // maximum duration hours
$limits['links'] = 0;   //maximum sharing links per user

// extra
$limits['nolimit'] = 0; // allow unlimited duration (=~ 100 years) with duration = 0 (the maximum duration limit is kept) [1 = yes | 0 = no]

// path on domain where a symlink to share.php can be found
// example: http://mydomain.com/share.php
$downloadpath = 'https://mehdisa.xyz/public/share.php';

`?>`
