### ISSUE TITLE
Update wiki for compile rtorrent

### ISSUE THREAD

**Issue by mattdinsdale** [xombiemp/ultimate-torrent-setup#64]
please add the following to the compile rtorrent section. 

apt install libxmlrpc-core-c3-dev

It removes the compile error with xmlrpc-c

**Comment by mehdi198080** [comment]
[Tue Jun 18 14:46:08.023952 2019] [php7:emerg] [pid 542] [client xx.xx.xx.xx:46944] PHP Parse error:  syntax error, unexpected '$XMLRPCMountPoint' (T_VARIABLE) in /var/www/rutorrent/conf/config.php o$

**Comment by mehdi198080** [comment]
I get this error command

**Comment by xombiemp** [comment]
I can confirm the compile instructions work as is.
