### ISSUE TITLE
Explain the Autotools part

### ISSUE THREAD

**Issue by Fronix** [xombiemp/ultimate-torrent-setup#66]
Hi,
So I didn't think the Autotools did anything except if i added a torrent to the watch directory and I dont use it so I disabled it. Now I ended up with it copying / into the torrent folder and messed up all my movies. Any way you could explain a bit exactly how it works because I don't see how the complete folder is used at all by either radarr or sonarr

**Comment by xombiemp** [comment]
Sonarr, Radarr and Lidarr are now configured to use the rTorrent provider rather than Blackhole. This means they don't use the Autotools to create the hardlink anymore.  You can still set up Autotools for other torrents outside of Sonarr, Radarr and Lidarr and the instructions mention this now.
