### ISSUE TITLE
Supplied rtorrent config uses depreciated commands as of v0.9

### ISSUE THREAD

**Issue by deafmute1** [xombiemp/ultimate-torrent-setup#67]
see https://github.com/rakshasa/rtorrent/wiki/rTorrent-0.9-Comprehensive-Command-list-(WIP).
Sed migration script here: https://github.com/rakshasa/rtorrent/wiki/RPC-Migration-0.9.

**Comment by xombiemp** [comment]
The rtorrent.rc file was updated to 0.9 syntax in 2017 with https://github.com/xombiemp/ultimate-torrent-setup/commit/54af394725c054521a895a721afc689deda9679a

I ran just ran the sed command with that sed file and the output contained no changes.

What commands specifically do you see that are deprecated?
