### ISSUE TITLE
Missing curl.

### ISSUE THREAD

**Issue by Dolkis** [xombiemp/ultimate-torrent-setup#68]
sudo apt install -y git build-essential automake libtool libcppunit-dev libcurl4-openssl-dev libsigc++-2.0-dev libncurses5-dev zlib1g-dev libssl-dev libchromaprint-tools zip unzip rar unrar mediainfo ffmpeg php-fpm php-geoip php-curl php-mbstring python python-setuptools

if the Ubuntu is a fresh install curl is not installed. So put in curl in the apt install -y command.

**Comment by xombiemp** [comment]
Added. Thanks
