### ISSUE TITLE
New caddy install

### ISSUE THREAD

**Issue by Dolkis** [xombiemp/ultimate-torrent-setup#69]
Ut says:
Install Caddy
sudo curl https://getcaddy.com | bash -s personal http.jwt,http.login

But in the Ubuntu terminal I am in the dir: /usr/local/src/rtorrent-0.9.8#

I think it shuld be
cd /usr/local/src ?

**Comment by xombiemp** [comment]
This has changed and is irrelevant now that we are using Caddy 2.
