### ISSUE TITLE
unpack and rtorrentToSickBeard doesn't work together

### ISSUE THREAD

**Issue by kamakamadaun** [xombiemp/ultimate-torrent-setup#7]
I could not get automatic unpack to work at all until I disabled rtorrentToSickBeard in the config file.
Any way to fix that?

**Comment by xombiemp** [comment]
None of my sources ever require unpacking so I've never run into this problem. The rtorrentToSickBeard script isn't technically needed.  Just enable Scan and Process in the Sickbeard post processing preferences and remove the line that calls it in the rtorrent.rc file.
