### ISSUE TITLE
Getting it to work with transdrone/transdroid

### ISSUE THREAD

**Issue by whytedwarf** [xombiemp/ultimate-torrent-setup#70]
I have tried everything that I can to get transdroid to work with rutorrent but it just won't cooperate. I know that it's outside of the scope of this project but I figured you'd probably be the best person to ask. I have been successful in the past using the rpc mount point /rutorrent/plugins/httprpc/actions.php
I'm not sure if this has to do with caddy not accepting the login information or not. 

Any help or guidance you could provide would be greatly appreciated.

**Comment by xombiemp** [comment]
I'm not sure how Transdroid works, but the Caddy authentication is probably what is blocking it.  Maybe it works with Basic Auth?  You can set up Caddy so that Basic auth is used for that /rutorrent path and then maybe it would work.
