### ISSUE TITLE
xmlrpc-c changed source file

### ISSUE THREAD

**Issue by SmokeyBR** [xombiemp/ultimate-torrent-setup#72]
apparently the file on https://sourceforge.net/projects/xmlrpc-c/files/latest/download is no longer in gzip format or when i try to run 
`tar --no-same-owner -xzvf xmlrpc-c-*.tgz`

get error returned:
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by xombiemp** [comment]
This seems to be resolved now.
