### ISSUE TITLE
Changing to RTorrent client vs Torrent Blackhole causes auto imports to fail.

### ISSUE THREAD

**Issue by wgehalo** [xombiemp/ultimate-torrent-setup#73]
I believe the issue is related to torrents that have to be extracted.
Once they are extracted the extracted file only lives in /torrent/complete and not /torrent/download, so when the rTorrent client setup over RPC looks in that folder for a file to import it isn't there.

Previously this worked because the client was set to monitor the completed folder and periodically import the results. I think it's possible to completely eliminate the completed folder here, as well as using autowatch to move completed downloads.

All that should be necessary now using the rTorrent client RPC endpoint is a watch folder for torrent drops, and the download folder for downloading. Then set rTorrent to leave completed downloads alone and unpack in the /downloads folder.

Additionally this should not affect the torrent as long as hard link is selected for renaming/importing in sonarr/radarr.

**Comment by wgehalo** [comment]
Yep, I can confirm the above works to rectify the situation when dealing with torrents where the media must be unpacked.

The unpacker sticks the file in the original location under /download, this allows sonarr to see the file, and subsequently create a hardlink to the /Media folder, and rename it.

**Comment by wgehalo** [comment]
I can also confirm it works with a torrent that does not need unpacking.
Radarr successfully started the download, was informed of progress, and imported via hardlink, renaming in the process.

It feels kind of strange to eliminate the completed folder, but it's no longer needed from what I can tell. Please let me know if I'm missing something here.

**Comment by xombiemp** [comment]
You are correct.  In the guide I have some regex that is excluding the Sonarr/Radarr labels from the automove logic.  So the complete folder is not used for Sonarr/Radarr torrents, only manually added torrents.
Glad it's working for you to unpack to the download folder.
