### ISSUE TITLE
Wiki instructions wrong due to upstream file type change

### ISSUE THREAD

**Issue by UberLerd** [xombiemp/ultimate-torrent-setup#74]
The install Wiki has an error due to an upstream file type change.  I have reflected the necessary change for successful progression below.

**Compile xmlrpc**

cd /usr/local/src

sudo curl -LOJ https://sourceforge.net/projects/xmlrpc-c/files/latest/download

_sudo tar --no-same-owner -xzvf xmlrpc-c-*.tgz_
This needs to be changed to "sudo tar --no-same-owner **-xvf** xmlrpc-c-*.tgz"

sudo find . -type d -exec chmod a+rx {} \;

cd xmlrpc-c-*/

sudo ./configure

sudo make

sudo make install

**Comment by xombiemp** [comment]
This seems to be resolved now.
