### ISSUE TITLE
Access rights issues in brown-field installation

### ISSUE THREAD

**Issue by chortya** [xombiemp/ultimate-torrent-setup#76]
The imported content is not deleted from "complete" folder. Also I can't delete the sub-folders with the user in same group as the folders are created - "media".
Main torrent folder and all the subfolders are in "media" group.

**Comment by xombiemp** [comment]
The complete folder isn't used for Sonarr, Radarr or Lidarr anymore.  They files are imported with a hardlink created by the apps themselves.
