### ISSUE TITLE
Delete/remove individual packages/software.

### ISSUE THREAD

**Issue by joshernandez** [xombiemp/ultimate-torrent-setup#78]
Can you provide a script for each software you have scripts to install? My setup got completely broken and instead of starting everything from scratch, which would be a pain and almost a sin. Removing everything I did from this guide up until installing rTorrent would solve many of my issues, Or, maybe some sort of clean up guide, if not, point me somewhere I can achieve this, thanks.

**Comment by xombiemp** [comment]
I would suggest starting over.
