### ISSUE TITLE
PPA used

### ISSUE THREAD

**Issue by SmokeyBR** [xombiemp/ultimate-torrent-setup#84]
could i ask why u choose to use a ppa for php instalation instead of using apt to install php? also is there no need to build from source rtorrent in ubuntu 22.04 ?

**Comment by xombiemp** [comment]
Yeah, I used the ppa because it includes php-geoip. Otherwise, that wouldn't be available.
rtorrent compiled with xmlrpc-c is an included package and I didn't see a reason to build from source.
