### ISSUE TITLE
Need go as a dependency for update-caddy

### ISSUE THREAD

**Issue by pauldmccallum** [xombiemp/ultimate-torrent-setup#86]
When running update-caddy, the script fails with:

2023/07/21 11:42:39 [INFO] Initializing Go module
2023/07/21 11:42:39 [INFO] exec (timeout=-2562047h47m16.854775808s): go mod init caddy 
2023/07/21 11:42:39 [FATAL] exec: "go": executable file not found in $PATH
mv: cannot stat 'caddy': No such file or directory
Job for caddy.service failed because the control process exited with error code.
See "systemctl status caddy.service" and "journalctl -xeu caddy.service" for details.

The fix is to install go. I'd add this to your PreReqs step.

**Comment by pauldmccallum** [comment]
Sorry, should have added that  this is the Arch version

**Comment by xombiemp** [comment]
Go is installed as a dependency for yay earlier in the guide.
