### ISSUE TITLE
Initial login to Caddy shows Unauthorized - Arch Linux Version

### ISSUE THREAD

**Issue by pauldmccallum** [xombiemp/ultimate-torrent-setup#88]
Browsing to https://yourdomain.com/auth/settings/password and trying to log in as webadmin displays an Unauthorized page. I cannot get to the point where I even can enter a password.

**Comment by Aergernis** [comment]
Hi,
had the same problem (also on ubuntu)

i've added 1 lines to Caddyfile under `authentication portal myportal {`

```
	  cookie domain yourdomain.com
```
don't forget to change yourdomain.com to your needs

**Comment by xombiemp** [comment]
I can't reproduce.
