### ISSUE TITLE
No plain text secret given on install caddy

### ISSUE THREAD

**Issue by Aergernis** [xombiemp/ultimate-torrent-setup#89]
Hi,

when installing caddy, the default secret is genrated as hash in `users.json`, but it's not showing in plain text in journalcat

`caddy[10779]: {"level":"info","ts":1715685581.4268587,"logger":"security","msg":"created default admin user for the database","username":"webadmin","email":"webadmin@localdomain.local","roles":["authp/admin"]}`

as a work around i hashed a new password with `caddy hash-password -p <password>` in copy it to `users.json`

**Comment by xombiemp** [comment]
I've updated the archlinux guide.
